name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore podcastination-importer.sln

      - name: Build Solution
        run: |
          msbuild.exe podcastination-importer.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile