name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore podcastination-importer.sln

      - name: Build Solution
        run: |
          msbuild.exe podcastination-importer.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: podcastination-importer.zip
          path: podcastination-importer\bin\Release\netcoreapp3.1

      - name: Zip Build Artifact for Release
        uses: papeloto/action-zip@v1
        with:
          files: podcastination-importer\bin\Release\netcoreapp3.1
          dest: podcastination-importer.zip

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Add plugins for semantic release
        run: npm install semantic-release conventional-changelog-conventionalcommits @semantic-release/changelog @semantic-release/git

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: semantic-release
          GIT_COMMITTER_NAME: semantic-release
        run: npx semantic-release
